### ISSUE TITLE
update this repo?

### ISSUE THREAD

**Issue by gaming-hacker** [svn2github/pcre2#1]
it's out of date.

i've tried to make my own git repo but the server is down?

> svn: E170013: Unable to connect to a repository at URL 'svn://vcs.pcre.org/pcre2/code/trunk'
> svn: E000060: Can't connect to host 'vcs.pcre.org': Operation timed out

**Comment by Ptomaine** [comment]
According to the pcre.org's documentation, the SVN repository is located on the following resource:

> You can check out the PCRE2 source code via Subversion (or browse PCRE2 source code on-line):
> **svn co svn://vcs.exim.org/pcre2/code/trunk pcre**

**Comment by gaming-hacker** [comment]
hmm, interesting there's a typo on one of pcre's pages.

thanks
